Upgrade command
uyuni-project/uyuni-tools pull request #123
Opened 2024-01-16 13:45 UTC by mbussolotto

2024-02-08 10:57 UTC, cbosdo requested changes

2024-02-08 10:57 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +}
```suggestion
func ReadContainerData(scriptDir string) (string, string, string, error) {
	data, err := os.ReadFile(filepath.Join(scriptDir, "data"))
	if err != nil {
		return "", "", "", errors.New("failed to read data extracted from source host")
	}
	viper.SetConfigType("env")
	viper.ReadConfig(bytes.NewBuffer(data))
	return viper.GetString("Timezone"), viper.GetString("old_pg_version"), viper.GetString("new_pg_version"), nil
}
```

2024-02-08 10:57 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		log.Fatal().Err(err).Msgf("Failed to create temporary directory")
```suggestion
		return "", fmt.Errorf("Failed to create temporary directory: %s", err)
```

2024-02-08 10:57 UTC, cbosdo commented on shared/podman/images.go
> +}
```suggestion
func ShowAvailableTag(image string) ([]string, error) {
	log.Info().Msgf("Running podman image search --list-tags %s --format='{{.Tag}}'", image)

	out, err := utils.RunCmdOutput(zerolog.DebugLevel, "podman", "image", "search", "--list-tags", image, "--format='{{.Tag}}'")
	if err != nil {
		return []string{}, fmt.Errorf("cannot find any tag for image %s: %s", image, err)
	}

	tags := strings.Split(string(out), "\n")
	return tags, nil
}
```

2024-02-08 10:57 UTC, cbosdo commented on shared/podman/systemd.go
> +}
```suggestion
func GenerateSystemdConfFile(serviceName string, section string, body string) error {
	systemdFilePath := GetServicePath(serviceName)
	log.Info().Msgf("systemdFilePath: %s", systemdFilePath)

	systemdConfFolder := systemdFilePath + ".d"
	log.Info().Msgf("systemdConfFolder: %s", systemdConfFolder)
	if err := os.MkdirAll(systemdConfFolder, 0750); err != nil {
		return fmt.Errorf("failed to create %s folder: %s", systemdConfFolder, err)
	}

	systemdConfFilePath := path.Join(systemdConfFolder, section+".conf")

	log.Info().Msgf("systemdConfFilePath: %s", systemdConfFilePath)

	if utils.FileExists(systemdConfFilePath) {
		log.Warn().Msgf("File %s already exists. It will be override", systemdConfFilePath)
	}

	content := []byte("[" + section + "]" + "\n" + body + "\n")

	if err := os.WriteFile(systemdConfFilePath, content, 0644); err != nil {
		return fmt.Errorf("cannot write %s file: %s", systemdConfFilePath, err)
	}
	return nil
}
```

2024-02-08 10:59 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/podman.go
> +		Long: `List avaialable tag for and image
```suggestion
		Long: `List available tag for and image
```

2024-02-08 11:00 UTC, mbussolotto commented on build.sh
> +CGO_ENABLED=0 go build -ldflags "-X ${VERSION_NAME}=${tag}-${offset}" -o ./bin ./...
done

2024-02-08 13:17 UTC, mbussolotto commented on mgradm/cmd/migrate/kubernetes/utils.go
>  		migrationImageUrl, err := utils.ComputeImage(migrationImage.Name, flags.Image.Tag)
what do you mean ? `ComputeImage` it's required (I also had some changes on it) and I think migration flags might be still helpful, if user don't want to use the compute image

2024-02-08 13:21 UTC, mbussolotto commented on mgradm/cmd/inspect/kubernetes.go
> +	shared_kubernetes.RunPod(podName, serverImage, pullPolicy, command, overridesArgs...)
So am I :D , I missed it, thanks for checking

2024-02-08 13:28 UTC, mbussolotto commented on mgradm/cmd/inspect/nokubernetes.go
> +func NewCommand(globalFlags *types.GlobalFlags) *cobra.Command {
not sure if I get the point here, please check if now it's ok

2024-02-08 13:33 UTC, mbussolotto commented on mgradm/cmd/upgrade/kubernetes/utils.go
> +	upgrade_shared.SanityCheck(cnx, inspectedValues, serverImage)
yes, I missed that, thanks

2024-02-08 13:53 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
>  		migrationImageUrl, err := utils.ComputeImage(migrationImage.Name, flags.Image.Tag)
I mean it's here and a few lines below. I wonder if those two are redundant

2024-02-08 14:13 UTC, mbussolotto commented on mgradm/cmd/migrate/kubernetes/utils.go
>  		migrationImageUrl, err := utils.ComputeImage(migrationImage.Name, flags.Image.Tag)
Oh thanks, I didn't notice it

2024-02-08 14:31 UTC, mbussolotto commented on mgradm/cmd/upgrade/podman/podman.go
> +		},
So do you want to show the available tags always during upgrade command, am I right or I miss something?

2024-02-08 15:01 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/podman.go
> +		},
No it's only about using the helper function and `RunE`

2024-02-09 10:21 UTC, mbussolotto commented on shared/kubernetes/utils.go
> +func GetNode(appName string) (string, error) {
@cbosdo Also `GetNode` should be improved: it works fine only if one pod is running (and this might not be the case in future, or if `mgradm` command is killed)

2024-02-09 14:36 UTC, cbosdo requested changes

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/kubernetes/utils.go
> +		return fmt.Errorf("Error running container %s: %s", pgsqlFinalizeContainer, err)
```suggestion
		return fmt.Errorf("error running container %s: %s", pgsqlFinalizeContainer, err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/kubernetes/utils.go
> +		return fmt.Errorf("Cannot upgrade to image %s: %s", serverImage, err)
```suggestion
		return fmt.Errorf("cannot upgrade to image %s: %s", serverImage, err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/podman.go
> +		Long: `Upgrade a local server on podman
Not sure if it's worth keeping `Long` if it's the same content as `Short`

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/podman.go
> +		},
You should replace with a `RunE` and use the helper function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +		return fmt.Errorf("Failed to compute image URL")
```suggestion
		return fmt.Errorf("failed to compute image URL")
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +		return fmt.Errorf("Failed to create temporary directory")
```suggestion
		return fmt.Errorf("failed to create temporary directory")
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +		return fmt.Errorf("Cannot stop service %s", err)
```suggestion
		return fmt.Errorf("cannot stop service %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +	shared_podman.StopService(shared_podman.ServerService)
```suggestion
	err = shared_podman.StopService(shared_podman.ServerService)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +				return fmt.Errorf("Failed to compute image URL %s", err)
```suggestion
				return fmt.Errorf("failed to compute image URL %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +				return fmt.Errorf("Failed to compute image URL %s", err)
```suggestion
				return fmt.Errorf("failed to compute image URL %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +			return fmt.Errorf("Cannot generate postgresql database migration script %s", err)
```suggestion
			return fmt.Errorf("cannot generate postgresql database migration script %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +		return fmt.Errorf("Trying to downgrade postgresql from %s to %s", inspectedValues["current_pg_version"], inspectedValues["image_pg_version"])
```suggestion
		return fmt.Errorf("trying to downgrade postgresql from %s to %s", inspectedValues["current_pg_version"], inspectedValues["image_pg_version"])
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +		return fmt.Errorf("Cannot generate postgresql migration finalization script %s", err)
```suggestion
		return fmt.Errorf("cannot generate postgresql migration finalization script %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/kubernetes/install.go
> +		return fmt.Errorf("Failed to compute image URL")
```suggestion
		return fmt.Errorf("failed to compute image URL")
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/podman/podman.go
> +		return fmt.Errorf("Failed to run %s container: %s", name, err)
```suggestion
		return fmt.Errorf("failed to run %s container: %s", name, err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		return fmt.Errorf("ExecCommand failed %s", err)
```suggestion
		return err
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		return "", fmt.Errorf("Failed to generate %s", scriptName)
```suggestion
		return "", fmt.Errorf("failed to generate %s", scriptName)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		return "", fmt.Errorf("Failed to generate %s", scriptName)
```suggestion
		return "", fmt.Errorf("failed to generate %s", scriptName)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		return "", fmt.Errorf("Failed to create temporary directory: %s", err)
```suggestion
		return "", fmt.Errorf("failed to create temporary directory: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +		return "", fmt.Errorf("Failed to generate migration script: %s", err)
```suggestion
		return "", fmt.Errorf("failed to generate migration script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +var PgsqlRequiredVolumeMounts = []types.VolumeMount{
Maybe you should add a comment on these two variables to explain what they should be used for.

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +var PgsqlRequiredVolumes = []types.Volume{
The other variable I meant

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Failed to pulled image: %s", err)
```suggestion
		return fmt.Errorf("failed to pulled image: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +	return errors.New(fmt.Sprintf("Failed to find a ready replica for deployment %s in namespace %s after 60s", name, namespace))
```suggestion
	return fmt.Errorf("failed to find a ready replica for deployment %s in namespace %s after 60s", name, namespace)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +				return errors.New("Failed to pull image")
```suggestion
				return errors.New("failed to pull image")
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +			return fmt.Errorf("Failed to get events for pod %s", podName)
```suggestion
			return fmt.Errorf("failed to get events for pod %s", podName)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Cannot run kubectl %s: %s", args, err)
```suggestion
		return fmt.Errorf("cannot run kubectl %s: %s", args, err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Cannot get pods for %s: %s", filter, err)
```suggestion
		return fmt.Errorf("cannot get pods for %s: %s", filter, err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +			return fmt.Errorf("Replica to %d failed: %s", replica, err)
```suggestion
			return fmt.Errorf("replica to %d failed: %s", replica, err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return pods, fmt.Errorf("Cannot execute %s: %s", strings.Join(cmdArgs, string(" ")), err)
```suggestion
		return pods, fmt.Errorf("cannot execute %s: %s", strings.Join(cmdArgs, string(" ")), err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Pod %s replica is not %d in %s seconds: %s", podname, replica, strconv.Itoa(waitSeconds), err)
```suggestion
		return fmt.Errorf("pod %s replica is not %d in %s seconds: %s", podname, replica, strconv.Itoa(waitSeconds), err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +			return fmt.Errorf("Cannot execute %s: %s", strings.Join(cmdArgs, string(" ")), err)
```suggestion
			return fmt.Errorf("cannot execute %s: %s", strings.Join(cmdArgs, string(" ")), err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Cannot run %s using image %s: %s", command, image, err)
```suggestion
		return fmt.Errorf("cannot run %s using image %s: %s", command, image, err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return fmt.Errorf("Deleting pod %s. Status fails with error %s", podname, err)
```suggestion
		return fmt.Errorf("deleting pod %s. Status fails with error %s", podname, err)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +		return "", fmt.Errorf("Cannot find Node name for app %s", appName)
```suggestion
		return "", fmt.Errorf("cannot find Node name for app %s", appName)
```

2024-02-09 14:36 UTC, cbosdo commented on shared/utils/utils.go
> +			return name, fmt.Errorf("Tag missing on %s", name)
```suggestion
			return name, fmt.Errorf("tag missing on %s", name)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/kubernetes.go
> +		return fmt.Errorf("Failed to determine image. %s", err)
```suggestion
		return fmt.Errorf("failed to determine image. %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/kubernetes.go
> +		return map[string]string{}, fmt.Errorf("Failed to create temporary directory. %s", err)
```suggestion
		return map[string]string{}, fmt.Errorf("failed to create temporary directory. %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/kubernetes.go
> +		return map[string]string{}, fmt.Errorf("Cannot find node for app uyuni %s", err)
```suggestion
		return map[string]string{}, fmt.Errorf("cannot find node for app uyuni %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/kubernetes.go
> +		return map[string]string{}, fmt.Errorf("Cannot run inspect pod %s", err)
```suggestion
		return map[string]string{}, fmt.Errorf("cannot run inspect pod %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +		return fmt.Errorf("Failed to determine image. %s", err)
```suggestion
		return fmt.Errorf("failed to determine image. %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +			return fmt.Errorf("Failed to find current running image")
```suggestion
			return errors.New("Failed to find current running image")
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +		return fmt.Errorf("Inspect command failed %s", err)
```suggestion
		return fmt.Errorf("inspect command failed %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +		return fmt.Errorf("Cannot print inspect result %s", err)
```suggestion
		return fmt.Errorf("cannot print inspect result %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +		return map[string]string{}, fmt.Errorf("Failed to create temporary directory %s", err)
```suggestion
		return map[string]string{}, fmt.Errorf("failed to create temporary directory %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/shared/shared.go
> +		return fmt.Errorf("Failed to generate inspect script: %s", err)
```suggestion
		return fmt.Errorf("failed to generate inspect script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +		return fmt.Errorf("Failed to generater migration script: %s", err)
```suggestion
		return fmt.Errorf("failed to generater migration script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +			return fmt.Errorf("Cannot generate postgresql database migration script: %s", err)
```suggestion
			return fmt.Errorf("cannot generate postgresql database migration script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +			return fmt.Errorf("Failed to compute image URL")
```suggestion
			return errors.New("failed to compute image URL")
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +		return fmt.Errorf("Cannot generate postgresql migration finalization script: %s", err)
```suggestion
		return fmt.Errorf("cannot generate postgresql migration finalization script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +		return fmt.Errorf("Cannot setup SSL: %s", err)
```suggestion
		return fmt.Errorf("cannot setup SSL: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/kubernetes/utils.go
> +			return []string{}, fmt.Errorf("Failed to strip text part of CA certificate %s", err)
```suggestion
			return []string{}, fmt.Errorf("failed to strip text part of CA certificate %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/podman/utils.go
> +		return fmt.Errorf("Cannot generate migration script: %s", err)
```suggestion
		return fmt.Errorf("cannot generate migration script: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/migrate/podman/utils.go
> +			return fmt.Errorf("Failed to compute image URL: %s", err)
```suggestion
			return fmt.Errorf("failed to compute image URL: %s", err)
```

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/kubernetes.go
> +func InspectKubernetes(serverImage string, pullPolicy string) (map[string]string, error) {
Add a comment above this function and other exported functions: this is used for the go doc. See https://go.dev/blog/godoc

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/inspect/podman.go
> +func InspectPodman(serverImage string, pullPolicy string) (map[string]string, error) {
Add a comment above this function too

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/shared/shared.go
> +func CompareVersion(imageVersion string, deployedVersion string) int {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/cmd/upgrade/shared/shared.go
> +func SanityCheck(cnx *shared.Connection, inspectedValues map[string]string, serverImage string) error {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/podman/podman.go
> +func RunContainer(name string, image string, extraArgs []string, cmd []string) error {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +func GenerateFinalizePostgresMigrationScript(scriptDir string, RunAutotune bool, RunReindex bool, RunSchemaUpdate bool, RunDistroMigration bool, kubernetes bool) (string, error) {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +func ReadContainerData(scriptDir string) (string, string, string, error) {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on mgradm/shared/utils/exec.go
> +func RunningImage(cnx *shared.Connection, containerName string) (string, error) {
Add a comment for that function

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +func ReplicasTo(filter string, replica uint) error {
```suggestion
// Scale the number of replicas of the server.
func ReplicasTo(filter string, replica uint) error {
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +	args := []string{"scale", "deploy", "uyuni", "--replicas"}
We could probably use the `filter` in this command instead of `uyuni` to make it a bit more reusable in the future

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +func DeletePod(podname string) (string, error) {
```suggestion
Delete a kubernetes pod named podname.
func DeletePod(podname string) (string, error) {
```

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +	return string(out), nil
Do we really need the output of `kubectl` here?

2024-02-09 14:36 UTC, cbosdo commented on shared/kubernetes/utils.go
> +func GetNode(appName string) (string, error) {
Don't we have a similar function already implemented in the `Connection` object?

2024-02-09 14:36 UTC, cbosdo commented on shared/podman/images.go
> +func ShowAvailableTag(image string) ([]string, error) {
Add a comment here

2024-02-09 14:36 UTC, cbosdo commented on shared/podman/systemd.go
> +// Create new conf file
```suggestion
// Create new systemd service configuration file.
```

Note that `godoc` is picky about sentences: they need to end with a dot.

2024-02-09 14:36 UTC, cbosdo commented on shared/types/deployment.go
> +type VolumeMount struct {
Add some comments here to state that these are mapping the pod definition structure.

2024-02-09 14:36 UTC, cbosdo commented on shared/types/inspect.go
> +func InspectDataConstructor(variable string, cli string) InspectData {
```suggestion
func NewInspectData(variable string, cli string) InspectData {
```
Would be more go-ish

2024-02-12 08:02 UTC, cbosdo commented on mgradm/cmd/distro/cp.go
> +		return errors.New(fmt.Sprintf("Source %s does not exists", source))
This is the same as `return fmt.Errorf("Source %s does not exists", source))`

2024-02-12 16:19 UTC, cbosdo approved these changes

2024-02-20 12:53 UTC, merged