Remote debugging
uyuni-project/uyuni-tools pull request #21
Opened 2023-08-21 15:18 UTC by mbussolotto

2023-08-21 15:37 UTC, cbosdo commented on uyuniadm/cmd/migrate/utils.go
> -sed 's/address=[^:]*:/address={{ .SourceFqdn }}:/' -i /etc/sysconfig/tomcat;
These two lines may be needed in a different shape because of:
* wrong file for tomcat
* We need to replace the FQDN with `*` as we could have the legacy way to set that option on the source

These two lines need to be run for both Kubernetes and podman cases.

2023-08-21 16:19 UTC, mbussolotto commented on uyuniadm/cmd/migrate/utils.go
> -sed 's/address=[^:]*:/address={{ .SourceFqdn }}:/' -i /etc/sysconfig/tomcat;
it should be better now :)

2023-08-23 07:56 UTC, cbosdo approved these changes

2023-09-07 14:11 UTC, cbosdo requested changes
That code has changed home: look at the `templates.MigrateScriptTemplateData` definition

2023-09-07 14:22 UTC, mbussolotto commented
oh yes, I know, the changes in this PR are no longer valid, I restarted everything from scratch. I already identifies the `uyunictl` commands for doing that, I just need to create a new command `uyunictl --debug=[true|false]`.


The command to enable remote debugging is:
```
uyunictl exec "grep -q 'JAVA_OPTS=\" \$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=\*:8000,server=y,suspend=n\"' /etc/tomcat/conf.d/remote_debug.conf || echo 'JAVA_OPTS=\" \$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=*:8000,server=y,suspend=n\" ' >> /etc/tomcat/conf.d/remote_debug.conf"
uyunictl exec "grep -q 'JAVA_OPTS=\" \$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=\*:8001,server=y,suspend=n\"' /etc/rnn/taskomatic.conf || echo 'JAVA_OPTS=\" \$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=*:8001,server=y,suspend=n\" ' >> /etc/rnn/taskomatic.conf"
uyunictl exec "spacewalk-service restart"
```

The command to disable remote debugging is:

```
uyunictl exec "sed -i '/-Xdebug -Xrunjdwp:transport=dt_socket,address=\*:8000,server=y,suspend=n/d' /etc/tomcat/conf.d/remote_debug.conf"
uyunictl exec "sed -i '/-Xdebug -Xrunjdwp:transport=dt_socket,address=\*:8001,server=y,suspend=n/d' /etc/rnn/taskomatic.conf"
uyunictl exec "spacewalk-service restart"
```

2023-09-07 14:24 UTC, mbussolotto commented
and I'm evaluating to use template to fill `port` value

2023-09-07 15:57 UTC, mbussolotto commented on uyuniadm/cmd/debug/debug.go
> +		utils.Exec(globalFlags, "", false, false, []string{}, "spacewalk-service restart")
(I mean something else than `spacewalk-service restart`)

2023-09-08 12:25 UTC, cbosdo commented on uyuniadm/cmd/debug/debug.go
> +		utils.Exec(globalFlags, "", false, false, []string{}, "spacewalk-service restart")
I just saw it here too: there is a blocking call to `systemd-ask-password` somewhere. Only restarting tomcat and tasko would be enough, but for sure it would be nice to find out what that call tries to do

2023-09-08 14:48 UTC, mbussolotto commented on uyuniadm/cmd/debug/debug.go
> +		utils.Exec(globalFlags, "", false, false, []string{}, "spacewalk-service restart")
re-tested and it worked like a charm :)

2023-09-26 13:18 UTC, cbosdo commented
Closing in favor of https://github.com/uyuni-project/uyuni-tools/pull/55

2023-09-26 13:18 UTC, closed without merging