add uyuni attestation container for podman
uyuni-project/uyuni-tools pull request #253
Opened 2024-04-18 14:21 UTC by lucidd

## What does this PR change?

add support for coco attestation container to mgradm.

## Test coverage
- No tests

- [x] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/23556

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-04-18 16:48 UTC, mbussolotto reviewed
I added some comment, the rest looks fine (but let's wait for other review :) )

2024-04-18 16:48 UTC, mbussolotto commented on mgradm/cmd/install/podman/utils.go
> +			return fmt.Errorf("failed to compute image URL, %s", err)
Now that we have localization, all these errors needs to be inside `L` function (e.g. https://github.com/uyuni-project/uyuni-tools/blob/68cf416f14bd878c58bdafadd7fcc4c1657e7b1e/mgradm/shared/podman/podman.go#L66 . You need to import `. "github.com/uyuni-project/uyuni-tools/shared/l10n"` (e.g. https://github.com/uyuni-project/uyuni-tools/blob/68cf416f14bd878c58bdafadd7fcc4c1657e7b1e/mgradm/shared/podman/podman.go#L21C2-L21C54 )

2024-04-18 16:48 UTC, mbussolotto commented on mgradm/cmd/upgrade/podman/utils.go
> +	if err := shared_podman.GenerateSystemdConfFile("uyuni-server-attestation", "Service", "Environment=UYUNI_IMAGE="+serverImage); err != nil {
you can re-use `shared_podman.ServerAttestationService` instead of `"uyuni-server-attestation"`

2024-04-18 16:48 UTC, mbussolotto commented on mgradm/shared/podman/podman.go
> +Environment=database_password=spacewalk
if `database_connection`, `database_user` and `database_password` would not change, I'd put them in `attestationServiceTemplate`. The idea is to have the main service file with values that doesn't change and the folder with values that might change (e.g. `UYUNI_IMAGE`)

2024-04-18 16:49 UTC, mbussolotto commented on mgradm/cmd/install/podman/utils.go
> +			return fmt.Errorf("failed to compute image URL, %s", err)
(this is the reason why this test is failing https://github.com/uyuni-project/uyuni-tools/actions/runs/8739643458/job/23981418583?pr=253 )

2024-04-19 04:39 UTC, mcalmer commented on mgradm/shared/podman/podman.go
> +Environment=database_password=spacewalk
I think these values should change. What is the idea how to do this?

2024-04-19 10:26 UTC, mbussolotto commented on mgradm/shared/podman/podman.go
> +Environment=database_password=spacewalk
if they might change, this is ok. We might improve trying to have separate `conf` file for different type of variable.
We this change we would have `Service.conf` that contains:
```
Environment=UYUNI_IMAGE=THE_IMAGE_URL
Environment=database_connection=jdbc:postgresql://uyuni-server:5432/susemanager
Environment=database_user=spacewalk
Environment=database_password=spacewalk
```
Probably the best can be have an `image.conf` with :+1: 
```
Environment=UYUNI_IMAGE=THE_IMAGE_URL
```
and a `database.conf` with:
```
Environment=database_connection=jdbc:postgresql://uyuni-server:5432/susemanager
Environment=database_user=spacewalk
Environment=database_password=spacewalk
```
as you prefer, this approach is good as well.

2024-04-19 14:07 UTC, lucidd commented on mgradm/shared/podman/podman.go
> +Environment=database_password=spacewalk
those values can be changed as they refer to the uyuni db. Another reason to have it all here in one place is that the service file is world readable while this dropin config directory is not.

2024-04-23 11:39 UTC, mcalmer requested changes
I added a domain for the internal network. I think we should use this everywhere.
I wonder if it works without, but maybe yes, as it than only use the short hostname.

2024-04-23 11:39 UTC, mcalmer commented on mgradm/shared/templates/attestationServiceTemplate.go
> +	--hostname {{ .NamePrefix }}-server-attestation \
I think we should use the same internal domain as the server-image has.
```suggestion
	--hostname {{ .NamePrefix }}-server-attestation.mgr.internal \
```

2024-04-23 11:39 UTC, mcalmer commented on mgradm/shared/podman/podman.go
> +Environment=database_connection=jdbc:postgresql://uyuni-server:%d/%s
```suggestion
Environment=database_connection=jdbc:postgresql://uyuni-server.mgr.internal:%d/%s
```

We use now a domain for the internal network.

2024-04-24 14:03 UTC, cbosdo commented on mgradm/cmd/restart/podman.go
> +	return podman.RestartService(podman.ServerAttestationService)
Wouldn't that fail if the number of replicas is set to 0?  I would check if the service is defined first

2024-04-24 14:03 UTC, cbosdo commented on mgradm/cmd/start/podman.go
> +	err := podman.StartService(podman.ServerAttestationService)
Same here... wouldn't that fail if the number of replicas is set to 0? I would check if the service is defined first

2024-04-24 14:05 UTC, cbosdo commented on mgradm/cmd/stop/podman.go
> +	err := podman.StopService(podman.ServerAttestationService)
Same here... wouldn't that fail if the number of replicas is set to 0? I would check if the service is defined first

2024-04-24 14:06 UTC, cbosdo commented on mgradm/cmd/uninstall/podman.go
> +	podman.UninstallService(podman.ServerAttestationService, !flags.Force)
Same here... wouldn't that fail if the number of replicas is set to 0? I would check if the service is defined first

2024-04-24 14:06 UTC, cbosdo commented on mgradm/cmd/uninstall/podman.go
> +	podman.DeleteContainer(podman.ServerAttestationService, !flags.Force)
Same here... wouldn't that fail if the number of replicas is set to 0? I would check if the service is defined first

2024-04-24 14:06 UTC, cbosdo commented on mgradm/cmd/upgrade/podman/utils.go
> +	}
Same here... wouldn't that fail if the number of replicas is set to 0? I would check if the service is defined first

2024-04-24 14:19 UTC, cbosdo commented on mgradm/shared/templates/attestationServiceTemplate.go
> +`
You may want to create a systemd unit template as documented in [systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#):

>Unit names can be parameterized by a single argument called the "instance name". The unit is then constructed based on a "template file" which serves as the definition of multiple services or other units. A template unit must have a single "@" at the end of the unit name prefix (right before the type suffix). The name of the full unit is formed by inserting the instance name between "@" and the unit type suffix. In the unit file itself, the instance parameter may be referred to using "%i" and other specifiers, see below.

This would allow you to spawn multiple instances of the same coco container to get multiple replicas.

The template could look like this:

```suggestion
const attestationServiceTemplate = `# uyuni-server-attestation.service, generated by mgradm
# Use an uyuni-server-attestation.service.d/local.conf file to override

[Unit]
Description=Uyuni server attestation container service
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
ExecStartPre=/bin/rm -f %t/uyuni-server-attestation-%i.pid %t/%n.ctr-id
ExecStartPre=/usr/bin/podman rm --ignore --force -t 10 {{ .NamePrefix }}-server-attestation-%i
ExecStart=/usr/bin/podman run \
	--conmon-pidfile %t/uyuni-server-attestation-%i.pid \
	--cidfile=%t/%n-%i.ctr-id \
	--cgroups=no-conmon \
	--sdnotify=conmon \
	-d \
	-e database_connection  \
	-e database_user \
	-e database_password \
	--replace \
	--name {{ .NamePrefix }}-server-attestation-%i \
	--hostname {{ .NamePrefix }}-server-attestation.mgr.internal \
	--network {{ .Network }} \
	${UYUNI_IMAGE}

ExecStop=/usr/bin/podman stop --ignore -t 10 --cidfile=%t/%n-%i.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore -t 10 --cidfile=%t/%n-%i.ctr-id
PIDFile=%t/uyuni-server-attestation-%i.pid
TimeoutStopSec=60
TimeoutStartSec=60
Type=forking

[Install]
WantedBy=multi-user.target default.target
`
```

I'm not sure about the `-%i` variable. I'm also not sure if the hostname should include the variable and if the folder to override the properties would stay the same.

2024-04-24 14:20 UTC, cbosdo commented on mgradm/shared/utils/cmd_utils.go
> +		fmt.Sprintf("Image for %s container, overrides the namespace if set", container))
```suggestion
		fmt.Sprintf(L("Image for %s container, overrides the namespace if set"), container))
```

2024-04-24 14:21 UTC, cbosdo commented on mgradm/shared/utils/cmd_utils.go
> +		fmt.Sprintf("Tag for %s container, overrides the global value if set", container))
```suggestion
		fmt.Sprintf(L("Tag for %s container, overrides the global value if set"), container))
```

2024-04-24 14:23 UTC, cbosdo commented on mgradm/shared/templates/attestationServiceTemplate.go
> +	--hostname {{ .NamePrefix }}-server-attestation \
Fixed

2024-04-24 14:23 UTC, cbosdo commented on mgradm/shared/podman/podman.go
> +Environment=database_connection=jdbc:postgresql://uyuni-server:%d/%s
Fixed

2024-04-24 14:59 UTC, mcalmer approved these changes
my concerns are addressed. I will leave the rest for the experts :-)

2024-04-24 15:27 UTC, lucidd commented on mgradm/shared/templates/attestationServiceTemplate.go
> +`
the plan was to use systemd templates for this but since we don't want to add support for more then one container until later, i will leave this out for now.

2024-04-25 15:11 UTC, merged