add missing metrics ports for prometheus
uyuni-project/uyuni-tools pull request #26
Opened 2023-09-08 08:39 UTC by rjmateus

Add missing ports for JMX export for prometheus:
https://documentation.suse.com/suma/4.3/en/suse-manager/administration/monitoring.html

2023-09-08 09:12 UTC, cbosdo requested changes
Could you please also add them to `shared/utils/pod.go` in the `TCP_PORTS`? I should refactor the podman code to use this structure too, but that can be in a separate PR. Just mind that the name in that struct is used by Kubernetes and needs to be short... but I can't remember the limit

2023-09-08 11:56 UTC, cbosdo commented on shared/utils/pod.go
> +	newPortMap("client-metrics", 9100, 9100),
From the name it looks like`node-metrics` and `client-metrics` are the same things. IIRC I had to use port 9101 because 9100 is already used by traefik on k3s.

2023-09-08 11:57 UTC, cbosdo reviewed
Just a doubt on the 9100 port

2023-09-08 12:36 UTC, rjmateus commented on shared/utils/pod.go
> +	newPortMap("client-metrics", 9100, 9100),
I have adjusted the helm definition: https://github.com/uyuni-project/uyuni/commit/afa18797d98b5b02c25cc54442f442defebd7cff

2023-09-11 08:59 UTC, witekest commented on shared/utils/pod.go
> +	newPortMap("client-metrics", 9100, 9100),
As replied per email. We should consider dropping node exporter in favor of cAdvisor.

2023-09-14 14:49 UTC, cbosdo reviewed
I'll change that one PR

2023-09-14 14:49 UTC, cbosdo commented on shared/utils/pod.go
> +	newPortMap("tomcat-JMX-metrics", 5557, 5557),
These names should be less than 15 characters long and lowercase:
```
Error: INSTALLATION FAILED: 2 errors occurred:
	* Service "traefik" is invalid: [spec.ports[6].targetPort: Invalid value: "taskomatic-jmx-metrics": must be no more than 15 characters, spec.ports[8].targetPort: Invalid value: "tomcat-jmx-metrics": must be no more than 15 characters]
	* Deployment.apps "traefik" is invalid: [spec.template.spec.containers[0].ports[7].name: Invalid value: "taskomatic-jmx-metrics": must be no more than 15 characters, spec.template.spec.containers[0].ports[10].name: Invalid value: "tomcat-jmx-metrics": must be no more than 15 characters]
```

2023-09-14 16:48 UTC, cbosdo approved these changes

2023-09-14 16:49 UTC, merged