backend flag required in mgrpxy start
uyuni-project/uyuni-tools pull request #298
Opened 2024-05-08 09:27 UTC by mbussolotto

## What does this PR change?

see the title

## Test coverage
- No tests

- [x] **DONE**

## Links

Issue(s): #

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-05-08 09:41 UTC, mcalmer approved these changes

2024-05-13 09:17 UTC, cbosdo requested changes

2024-05-13 09:17 UTC, cbosdo commented on shared/connection.go
>  					if kubernetes.HasHelmRelease("uyuni", clusterInfos.GetKubeconfig()) {
Something like this will probably be needed if the proxy is installed on kubernetes

```suggestion
					if kubernetes.HasHelmRelease("uyuni", clusterInfos.GetKubeconfig()) || kubernetes.HasHelmRelease("uyuni-proxy", clusterInfos.GetKubeconfig()) {
```

2024-05-13 09:36 UTC, cbosdo approved these changes

2024-05-15 13:12 UTC, merged