trim string before compare it
uyuni-project/uyuni-tools pull request #299
Opened 2024-05-09 13:06 UTC by mcalmer

## What does this PR change?

When reading from file, we need to trim the string before we can compare it.
This will fix the IPv6 enabled detection

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Issue(s): #

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-05-09 13:07 UTC, Bischoff requested changes
bug number is 1224080, not 1224081

2024-05-09 13:09 UTC, mcalmer commented
> bug number is 1224080, not 1224081

yes, just fixed it

2024-05-09 13:09 UTC, Bischoff approved these changes
thanks for the changelog fix

2024-05-10 08:05 UTC, mbussolotto approved these changes
LGTM

2024-05-10 08:11 UTC, srbarrios commented
We agreed on not merging this until RC submissions are ready, otherwise releng will need to re-tag them again.

2024-05-10 10:31 UTC, Bischoff commented
@srbarrios it's making my debugging a nightmare... :crying_cat_face:

2024-05-13 07:08 UTC, cbosdo reviewed
`strings.TrimSpace()` is the function you need.

2024-05-13 07:08 UTC, cbosdo commented on shared/utils/utils.go
> +	return strings.Trim(string(ReadFile(file)), "\n") != "0"
```suggestion
	return strings.TrimSpace(string(ReadFile(file))) != "0"
```

2024-05-13 08:56 UTC, cbosdo approved these changes

2024-05-15 13:44 UTC, merged