Do not enable dns plugin for proxy podman network
uyuni-project/uyuni-tools pull request #301
Opened 2024-05-10 13:44 UTC by aaannz

## What does this PR change?

Based on @mbussolotto backend detection fix!

We do not need inter-container hostname desolution for proxy as we just use localhost in the pod. This also fixed currently broken aardvark behavior.

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/24305

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-05-13 09:07 UTC, cbosdo requested changes
Is this PR a collection of other PRs?

2024-05-13 09:07 UTC, cbosdo commented on shared/connection.go
>  					if kubernetes.HasHelmRelease("uyuni", clusterInfos.GetKubeconfig()) {
Not tested, but this is likely to be needed too if the proxy container is deployed on kubernetes:

```suggestion
					if kubernetes.HasHelmRelease("uyuni", clusterInfos.GetKubeconfig()) || kubernetes.HasHelmRelease("uyuni-proxy", clusterInfos.GetKubeconfig()) {
```

2024-05-13 09:07 UTC, cbosdo commented on shared/podman/network.go
> +	args := []string{"network", "create", "--disable-dns"}
inter-container resolution will be needed for the server for hub-xmlrpc-api and the coco attestation container. If you really have to disable it, then please only do it on the proxy, but still that smells bad.

2024-05-13 09:07 UTC, cbosdo commented on mgrpxy/cmd/start/start.go
> +	utils.AddBackendFlag(startCmd)
In theory the backend flag should only be used to help the detection. The expected cases for it are when both `kubectl` and `podman` are installed on the machine (yes, it happens in very rare cases for `mgrctl`) or if the installation is broken. For a good user experience `start` should not need such a flag... if it does then we need to find why and fix it.

2024-05-13 09:10 UTC, mbussolotto commented
> Is this PR a collection of other PRs?

This PR contains the changes I made here https://github.com/uyuni-project/uyuni-tools/pull/298

2024-05-13 09:33 UTC, cbosdo commented on mgrpxy/cmd/start/start.go
> +	utils.AddBackendFlag(startCmd)
> Fine for me. The detection was broken on start cause of the other changes in this PR, not this one. But if `For a good user experience start should not need such a flag` probably we should remove `AddBackendFlag` at all ??

For this particular command, I'ld say yes we can remove it

2024-05-13 10:12 UTC, aaannz commented on shared/podman/network.go
> +	args := []string{"network", "create", "--disable-dns"}
Added a boolean which will differentiate between proxy and server networks. I don't think removing dns plugin in proxy network is bad idea. We don't need it and so we can spare some small cycles not doing this indirect dns queries.

2024-05-14 07:34 UTC, cbosdo commented on shared/podman/network.go
> +	args := []string{"network", "create", "--disable-dns"}
Looks good to me

2024-05-14 07:35 UTC, cbosdo commented
you would need to rebase on PR #298 since Michele addressed the comments there.

2024-05-15 13:38 UTC, aaannz commented
Rebased. I don't know why localization test is failing.

2024-05-15 14:11 UTC, cbosdo commented
> Rebased. I don't know why localization test is failing.

This is an issue with a PR Michele just merged. Could you please rebase on latest `main` as it's been fixed there?

2024-05-15 14:18 UTC, aaannz commented
Done. Thanks

2024-05-15 14:54 UTC, cbosdo approved these changes

2024-05-17 09:06 UTC, mbussolotto approved these changes

2024-05-17 10:41 UTC, merged