coco attestation container impovements
uyuni-project/uyuni-tools pull request #303
Opened 2024-05-13 13:18 UTC by lucidd

## What does this PR change?

This adds support for multiple instances of the confidential computing attestation container and a scale command to adjust the replicas.

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added

- [ ] **DONE**

## Links

Issue(s): #

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-05-13 14:22 UTC, mbussolotto requested changes
I left some comment, most of them are just about missing comments or return value.
Besides that:
- is it right to not have server attestation for uyuni on kubernetes?
- is there any better way to scale podman (maybe using `pod`?
cc @cbosdo

2024-05-13 14:31 UTC, lucidd commented on mgradm/cmd/scale/podman.go
> +	if service == "uyuni-server-attestation" {
i wasn't sure if we want to use the full service name here since its quite long or rather a shorter alias. I'm open for suggestions.

2024-05-13 15:36 UTC, lucidd commented on mgradm/cmd/status/podman.go
> +		utils.RunCmdStdMapping(zerolog.DebugLevel, "systemctl", "status", "--no-pager", podman.ServerService)
not sure if checking the error in this case makes sense since systemctl returns non 0 status codes for cases that are not errors i.e 3 in case the service is not running. This currently leads to this message `Error: failed to get status of the server service: exit status 3` being printed at the end of a successful status run. If the underlying command has a real error there should still be the forwarded stderr printed for more context.

2024-05-14 07:55 UTC, cbosdo commented on mgradm/cmd/status/podman.go
> +		println() // add an empty line between the previous logs and this one
and it wouldn't make sense to log an empty message in the log file. BTW the logger logs to both the log file and stdout

2024-05-14 07:55 UTC, cbosdo commented on mgradm/shared/coco/coco.go
> +func CurrentReplicaCount(name string) int {
I would move this function to the `shared/podman/systemd.go` since that is generic enough to be used by other containers in the future

2024-05-14 07:55 UTC, cbosdo commented on mgradm/shared/coco/coco.go
> +func ScaleService(replicas int, name string) error {
Same for this one: this is generic enough to be moved to `systemd.go`.

2024-05-14 07:55 UTC, cbosdo commented on mgradm/cmd/scale/kubernetes.go
> +	return errors.New(L("kubernetes not supported yet"))
We would need to think about the coco pod definition in server helm chart. There should be a deployment just for the coco attestation image and here all you would need to do is run `kubectl scale --replicas %d -n thenamespace deploy/coco-attestation` .

If you don't want to do it now, please add a card to add kubernetes support of the coco attestation image.

2024-05-14 07:58 UTC, cbosdo commented
>     * is it right to not have server attestation for uyuni on kubernetes?

It's not right, but we can afford doing it later, still I don't like skipping kubernetes parts for too long as that means we could overlook important differences with the podman implementation.

>     * is there any better way to scale podman (maybe using `pod`?

Sadly no, there is no better way. podman doesn't have an equivalent of kubernetes `deployment` or ` replicaSet`.

2024-05-15 14:01 UTC, cbosdo reviewed
You'll see quite some changes after a rebase on master. The PR looks good, but I added suggestions for changes after the new l10n rework that has been merged.

2024-05-16 09:46 UTC, cbosdo reviewed
One forgotten `utils.Errorf()` and some suggestion on the supported containers error / help.

2024-05-16 09:46 UTC, cbosdo commented on mgradm/cmd/scale/scale.go
> +		Long:    L("Adjust the replicas for container that supports it."),
Shouldn't we add a list of containers that supports it in the Long help? I already see people complaining because `mgradm scale --replicas 2 uyuni-server`  doesn't work

2024-05-16 09:46 UTC, cbosdo commented on mgradm/cmd/scale/podman.go
> +	return fmt.Errorf(L("Unknown service name: %s"), service)
```suggestion
	return fmt.Errorf(L("service not allowing to be scaled: %s"), service)
```

2024-05-16 09:46 UTC, cbosdo commented on mgradm/cmd/uninstall/podman.go
> +		return fmt.Errorf(L("cannot delete confidential computing attestation instances: %s"), err)
```suggestion
		return utils.Errorf(err, L("cannot delete confidential computing attestation instances"))
```

2024-05-16 09:59 UTC, lucidd commented on mgradm/cmd/scale/scale.go
> +		Long:    L("Adjust the replicas for container that supports it."),
makes sense. how about 
`Adjust the replicas for containers that support it. Supported containers: uyuni-server-attestation` ?

2024-05-16 11:28 UTC, cbosdo commented on mgradm/cmd/scale/scale.go
> +		Long:    L("Adjust the replicas for container that supports it."),
You can use multiline strings using backticks. After thinking about the wording again, we should probably name those differently than containers: in the kubernetes world this would address a `deployement` or `replicaSet` and the `container` is a different concept. Service isn't much better since it is the thing that exposes the network ports of the pods in the cluster...

```suggestion
		Short:   L("Adjust the replicas for services that supports it."),
		Long:    L(`Adjust the replicas for services that supports it.

Supported services:
  - uyuni-server-attestation
`),
```

2024-05-16 11:38 UTC, lucidd commented on mgradm/cmd/scale/scale.go
> +		Long:    L("Adjust the replicas for container that supports it."),
it will always be confusing since the terminology of one backend will never match the other backend.

2024-05-16 12:39 UTC, cbosdo commented on mgradm/cmd/scale/scale.go
> +		Long:    L("Adjust the replicas for container that supports it."),
> it will always be confusing since the terminology of one backend will never match the other backend.

Yes, but you'll have multiple containers for the same coco attestation, so even for `podman` case that would be confusing as the real containers will be `coco-attestation-%d`

2024-05-16 15:47 UTC, cbosdo commented on mgradm/cmd/scale/scale.go
> +	cmd.Flags().Int("replicas", 0, L("How many replicas of a container should be started."))
```suggestion
	cmd.Flags().Int("replicas", 0, L("How many replicas of a service should be started."))
```

2024-05-17 08:35 UTC, cbosdo approved these changes

2024-05-17 08:38 UTC, mbussolotto approved these changes
LGTM

2024-05-17 11:38 UTC, merged