supportconfig file name with date to avoid conflicts
uyuni-project/uyuni-tools pull request #321
Opened 2024-05-18 16:13 UTC by rjmateus

## What does this PR change?

Implements: https://github.com/uyuni-project/uyuni-tools/issues/318

Change the behavior of -o flag to define the path and not the filename. 
Supportconfig filename contains the hostname and data, to avoid conflicts and identify the machine.

TODO: we need to change the way the tar file is made, and save all files in a directory, to avoid conflicts when exported by supports.

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added

- [ ] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni-tools/issues/318

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-05-21 05:01 UTC, cbosdo requested changes

2024-05-21 05:01 UTC, cbosdo commented on mgradm/cmd/support/config/extractor.go
> +	supportFilePath := fmt.Sprintf("%s/%s.tar.gz", flags.Output, supportFileName)
```suggestion
	supportFilePath := path.Join(flags.Output, supportFileName)
```
Using `path.Join()` is better. Adding the `tar.gz` suffix to the result of `getSupportConfigFileSaveName()` would be more consistent.

2024-05-21 05:01 UTC, cbosdo commented on mgradm/cmd/support/config/extractor.go
> +	return fmt.Sprintf("scc_%s_%s", hostname, now.Format("20060102_1504"))
```suggestion
	return fmt.Sprintf("scc_%s_%s.tar.gz", hostname, now.Format("20060102_1504"))
```

2024-05-21 05:01 UTC, cbosdo commented on mgradm/cmd/support/config/extractor.go
> +		if err := tarball.AddFile(file, fmt.Sprintf("%s/%s", supportFileName, path.Base(file))); err != nil {
```suggestion
		if err := tarball.AddFile(file, path.Join(supportFileName, path.Base(file))); err != nil {
```

2024-05-21 15:01 UTC, rjmateus commented on mgradm/cmd/support/config/extractor.go
> +	supportFilePath := fmt.Sprintf("%s/%s.tar.gz", flags.Output, supportFileName)
the variable `supportFileName` is also used to define the path for files inside the tar file. If we add the extension to that it will also land inside the tar file and the extract folder will have it on the name. This was the reason I added the extension outside

2024-05-21 15:01 UTC, rjmateus commented on mgradm/cmd/support/config/extractor.go
> +	supportFilePath := fmt.Sprintf("%s/%s.tar.gz", flags.Output, supportFileName)
I will change the code to use path.join

2024-05-21 15:04 UTC, cbosdo commented on mgradm/cmd/support/config/extractor.go
> +	supportFilePath := fmt.Sprintf("%s/%s.tar.gz", flags.Output, supportFileName)
> the variable `supportFileName` is also used to define the path for files inside the tar file. If we add the extension to that it will also land inside the tar file and the extract folder will have it on the name. This was the reason I added the extension outside

OK, I oversaw this, thanks for explaining

2024-05-21 17:02 UTC, rjmateus commented on mgradm/cmd/support/config/extractor.go
> +	supportFilePath := fmt.Sprintf("%s/%s.tar.gz", flags.Output, supportFileName)
changed

2024-05-21 17:02 UTC, rjmateus commented on mgradm/cmd/support/config/extractor.go
> +		if err := tarball.AddFile(file, fmt.Sprintf("%s/%s", supportFileName, path.Base(file))); err != nil {
changed

2024-05-22 06:08 UTC, cbosdo approved these changes

2024-05-22 07:45 UTC, merged