add mgrpxy squid clear command
uyuni-project/uyuni-tools pull request #352
Opened 2024-06-07 15:35 UTC by rjpmestre

## What does this PR change?

This PR provides a new mgrpxy command so users can clear squid cache on demand.

## Test coverage
- No tests: manual tests

- [X] **DONE**

## Links

Issue(s): #146 

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-06-11 12:48 UTC, mbussolotto requested changes

2024-06-18 12:27 UTC, mbussolotto commented on shared/podman/utils.go
> +				log.Error().Err(err).Msgf(L("Failed to create volume %s"), name)
you should do somethink like https://github.com/uyuni-project/uyuni-tools/blob/51722a4c1c7c03d38690e0d9db3578fc7b346f74/mgradm/cmd/install/podman/utils.go#L88

2024-06-18 12:30 UTC, mbussolotto commented on mgrpxy/cmd/squid/kubernetes.go
> +	err = utils.RunCmdStdMapping(zerolog.DebugLevel, "kubectl", "exec", podName, "-c", "squid", "--", "find", "/var/cache/squid", "-mindepth", "1", "-delete")
I need an opinion from @cbosdo here :). We've never used `kubectl exec` until now, so I'm not sure if there's any limit or better way for doing it

2024-06-24 09:42 UTC, cbosdo commented on mgrpxy/cmd/squid/kubernetes.go
> +	err = utils.RunCmdStdMapping(zerolog.DebugLevel, "kubectl", "exec", podName, "-c", "squid", "--", "find", "/var/cache/squid", "-mindepth", "1", "-delete")
We use it in a few places. I see two problems here:

* `Connection.Exec()` should be extended to work in the proxy too and use here.

* There is no namespace selected and thus the `default` will be picked while the proxy may be installed in another one. You'll need to detect the namespace first and then add it with `'-n', namespace` to the kubectl command options.

It also smells like `Connection.Exec()` and a few other places in our code don't handle the namespace correctly.

2024-06-24 09:42 UTC, cbosdo commented on mgrpxy/cmd/squid/podman.go
> +	if err := podman.CreateVolume(volumeName, false); err != nil {
Couldn't you handle the clear as done in Kubernetes? If that works it avoids volumes handling...

2024-06-28 15:00 UTC, rjpmestre commented on mgrpxy/cmd/squid/kubernetes.go
> +	err = utils.RunCmdStdMapping(zerolog.DebugLevel, "kubectl", "exec", podName, "-c", "squid", "--", "find", "/var/cache/squid", "-mindepth", "1", "-delete")
I think i addressed your concerns. I ended up expanding the Connection struct so we can explicitly target a namepace and/or container.

2024-07-01 08:36 UTC, cbosdo commented on shared/connection.go
> +func NewKubernetesConnection(namespace string, kubernetesFilter string, kubernetesContainer string) *Connection {
I would probably have the `kubernetesContainer`  left as a parameter of the `Exec()` method so you could use the same connection to deal with multiple containers of the same pod. But that can be changed later if that hurts.

2024-07-01 08:40 UTC, cbosdo commented on shared/connection.go
> +			namespace, namespaceErr = kubernetes.GetNamespace(c.kubernetesFilter)
You surely want to store the found namespace in the connection object...
```suggestion
			namespace, namespaceErr = kubernetes.GetNamespace(c.kubernetesFilter)
			c.namespace = namespace
```

2024-07-01 08:40 UTC, cbosdo commented on shared/kubernetes/kubernetes.go
> +func GetNamespace(kubernetesFilter string) (string, error) {
You could even have that function in the `Connection` object itself.

2024-07-01 08:41 UTC, cbosdo commented on mgrpxy/cmd/status/kubernetes.go
> +	namespace, err := kubernetes.GetNamespace("uyuni-proxy")
I'm fine with such a change, but could you please kick away the other `FindNamespace()` uses to replace them with your new function?

2024-07-02 20:36 UTC, rjpmestre commented on mgrpxy/cmd/status/kubernetes.go
> +	namespace, err := kubernetes.GetNamespace("uyuni-proxy")
I was looking to find an elegant of doing but: 
- [HelmUnistall](https://github.com/uyuni-project/uyuni-tools/pull/352/files#diff-8666b3094e209ad406b9a5116fc2250b2e6666ffb4ef1ae6dfd2c2e9016085fcR65) uses it. 
- I did start by merging the content of both methods. It resulted in a method with a high cognitive complexity, hurting readability. 
For this reasons I just renamed the method for for something that goes with the method's specificity content, that is: to extract the namespace from a kubectl config file. 
Let me know what you think. I am under the impression you have quite a clear vision of what you'd like here and i'm just not being able to get it yet.

2024-07-02 20:40 UTC, rjpmestre commented on shared/connection.go
> +			namespace, namespaceErr = kubernetes.GetNamespace(c.kubernetesFilter)
Got you! Followed the same approach as [GetPodname](https://github.com/uyuni-project/uyuni-tools/pull/352/files#diff-f9195857a277d58e69d73592278875495daf2ddeacd42678cd2e64033b89fcc8L113-R158)

2024-07-03 07:57 UTC, cbosdo commented on mgrpxy/cmd/status/kubernetes.go
> +	namespace, err := kubernetes.GetNamespace("uyuni-proxy")
It's strange that we have several ways of getting the used namespace...

2024-07-03 07:58 UTC, cbosdo commented on shared/connection.go
> +			namespace, namespaceErr = kubernetes.GetNamespace(c.kubernetesFilter)
> Got you! Followed the same approach as [GetPodName()](https://github.com/uyuni-project/uyuni-tools/pull/352/files#diff-f9195857a277d58e69d73592278875495daf2ddeacd42678cd2e64033b89fcc8L113-R158)

Yes, but `GetPodName()` stores the value in its field too :wink:

2024-07-04 11:56 UTC, rjpmestre commented on mgrpxy/cmd/status/kubernetes.go
> +	namespace, err := kubernetes.GetNamespace("uyuni-proxy")
I gave it a go. Had to rework a bit the HelmUninstall method and it's callers. Let me know what you think of this approach

2024-07-04 12:40 UTC, cbosdo commented on shared/connection.go
> +// from the Helm release information from an also given kubeconfig file (path).
```suggestion
// from the Helm release information.
```
The kubeconfig path is just for the case it's installed in a non-standard place as k3s or rke2 are doing. If it's in `~/.kube/config` it can be empty.

2024-07-04 12:40 UTC, cbosdo commented on shared/connection.go
> +	}
I think we can get rid of this attempt and directly try getting it from helm.

2024-07-05 13:57 UTC, cbosdo commented on shared/connection.go
> +		log.Fatal().Err(cmdErr)
```suggestion
		return "", cmdErr
```

2024-07-05 13:57 UTC, cbosdo commented on mgrpxy/cmd/squid/podman.go
> +	return podman.EnableService(podman.ProxyService)
I'm not sure about this... In the running container you remove the cache files and recreate them... but enabling the service won't restart it... You may want `podman.RestartService(podman.ProxyService)` instead.

2024-07-05 13:57 UTC, cbosdo commented on mgrpxy/cmd/squid/kubernetes.go
> +	if _, err := cnx.ExecInKubernetesContainer("squid", "find", "/var/cache/squid", "-mindepth", "1", "-delete"); err != nil {
You have to read the function code to understand why you need it here and not the next exec. I would just expose a `Container` member in the Connection, set it before and run the regular `cnx.Exec()` everywhere. It would be more readable.

2024-07-05 13:57 UTC, cbosdo commented on shared/connection.go
> +	kubernetesContainer string
Why not merge `podmanContainer` and `kubernetesContainer` into an exposed `Container` ?

2024-07-10 13:10 UTC, rjpmestre commented on mgrpxy/cmd/squid/kubernetes.go
> +	if _, err := cnx.ExecInKubernetesContainer("squid", "find", "/var/cache/squid", "-mindepth", "1", "-delete"); err != nil {
Mixing this and the idea of merging podmanContainer and kubernetesContainer, I think we wouldn't even need to expose it.

2024-07-15 14:21 UTC, cbosdo commented on mgrpxy/cmd/squid/squid.go
> +		},
I would not have `squid` in the command name, but something more generic like:

```suggestion
		Use:   "cache",
		Short: L("Manage proxy cache"),
		Long:  L("Manage proxy cache"),
		Run: func(cmd *cobra.Command, args []string) {
			_ = cmd.Help()
		},
```

Maybe later we'll add a `--squid` parameter to `mgrpxy cache clear` to target which cache to clear.  There are different caches in a proxy. Even though the squid one is usually to one to clear, we shouldn't close the door to the others.

2024-07-16 09:39 UTC, rjpmestre commented on mgrpxy/cmd/squid/squid.go
> +		},
I see your point. Merged.

2024-07-16 14:43 UTC, cbosdo approved these changes

2024-07-19 16:02 UTC, closed without merging