Fqdn
uyuni-project/uyuni-tools pull request #394
Opened 2024-07-09 12:32 UTC by mbussolotto

## What does this PR change?

**add description**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added

- [ ] **DONE**

## Links

Issue(s): #

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-07-09 15:06 UTC, aaannz reviewed
Personally I am against pulling new dependency just for this, but seems like you have more plans with it 😄

The original bug was also about that our install script exits successfully despite wrong setup. Is that something we can catch in our tools or require change on uyuni side?

2024-07-09 15:06 UTC, aaannz commented on shared/utils/utils.go
> +	"github.com/go-playground/validator"
Are we going to use this deps for something else?

For me this seems like quite a big overkill for one regexp validation.

Validator is MIT license, so we can copy that regexp with attribution from https://github.com/go-playground/validator/blob/master/regexes.go#L58

2024-07-09 15:12 UTC, mbussolotto commented on shared/utils/utils.go
> +	"github.com/go-playground/validator"
make sense. Let me try to avoid to sue the library and add just the regex

2024-07-12 13:29 UTC, aaannz approved these changes
LGTM with one nitpick.

2024-07-12 13:29 UTC, aaannz commented on shared/utils/utils.go
> +var fqdnValid = regexp.MustCompile(`^([a-zA-Z0-9]{1}[a-zA-Z0-9-]{0,62})(\.[a-zA-Z0-9]{1}[a-zA-Z0-9-]{0,62})*?(\.[a-zA-Z]{1}[a-zA-Z0-9]{0,62})\.?$`)
Personally I would add a attribution link.
e.g. `// Taken from https://github.com/go-playground/validator/blob/2e1df48/regexes.go#L58`

2024-07-15 13:12 UTC, cbosdo requested changes

2024-07-15 13:12 UTC, cbosdo commented on mgradm/cmd/install/shared/shared.go
> +	_ = adm_utils.ExecCommand(zerolog.InfoLevel, cnx, "rm /tmp/setup.sh")
Why removing the error code here? Is this a dev leftover? and the error test after this would not behave as expected.

2024-07-15 13:46 UTC, mbussolotto commented on mgradm/cmd/install/shared/shared.go
> +	_ = adm_utils.ExecCommand(zerolog.InfoLevel, cnx, "rm /tmp/setup.sh")
mm actually this was intentional:
- I removed `rm $0` from the setup script: in this way the return code of the setup script is the return code of `mgr-setup`
- I added this line to remove the script and we want to remove it because this action should be perform this action also if the setup fails, that's why it is performed before checking the error of the setup script
- I ignored the error in `rm /tmp/setup.sh` because I don't think the installation should fails if we have problems just on removing the script.

At least this was the intention :D do you have better idea to implement it?

2024-07-15 14:28 UTC, cbosdo commented on mgradm/cmd/install/shared/shared.go
> +	_ = adm_utils.ExecCommand(zerolog.InfoLevel, cnx, "rm /tmp/setup.sh")
why not storing the result of `mgr-setup` in a variable and return it at the end to keep the rm in the script?

2024-07-16 15:09 UTC, cbosdo commented on mgradm/shared/templates/mgrSetupScriptTemplate.go
> +RESULT=$(/usr/lib/susemanager/bin/mgr-setup -s -n)
Is it the same then
```suggestion
/usr/lib/susemanager/bin/mgr-setup -s -n
RESULT=$?
```

2024-07-16 16:06 UTC, cbosdo approved these changes

2024-07-19 15:57 UTC, closed without merging