make registry flag a local variable, so it can be stored in config file
uyuni-project/uyuni-tools pull request #437
Opened 2024-08-26 11:45 UTC by mbussolotto

## What does this PR change?

make registry flag a local variable, so it can be stored in config file

## Test coverage

- [x] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/25141

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-09-02 14:40 UTC, cbosdo requested changes

2024-09-02 14:40 UTC, cbosdo commented on mgradm/shared/utils/cmd_utils.go
> +	cmd.Flags().String("registry", utils.DefaultRegistry, L("Registry"))
The help of that parameter is less verbose than it was. That flag is already confusing enough and should get proper help. Indicate what the value should be for instance.

2024-09-02 14:40 UTC, cbosdo commented on mgradm/shared/kubernetes/install.go
> +	globalFlags.Registry = image.Registry
Those are looking dangerous to me: rather than filling the old `globalFlags.Registry` I would update the code requiring the registry to use it from the new place. The is a high chance to forget to copy the value in some code in the future.

2024-09-02 14:40 UTC, cbosdo commented on mgradm/shared/utils/cmd_utils.go
> +	_ = utils.AddFlagHelpGroup(cmd, &utils.Group{ID: "dbupgrade-image", Title: L("Database Upgrade Image Flags (use --registry for registry)")})
I don't get what the added help really means

2024-09-02 14:40 UTC, cbosdo commented on mgrpxy/shared/utils/flags.go
> +	cmd.Flags().String("registry", utils.DefaultRegistry, L("Registry"))
Same here, the help could be better for a confusing parameter.

2024-09-02 14:40 UTC, cbosdo commented on shared/types/global.go
> +	Registry   string //set using local flag registry (from image group)
:scream: This it too dangerous...

2024-09-05 10:38 UTC, mbussolotto commented
closing it, changes will be addressed in https://github.com/uyuni-project/uyuni-tools/pull/445

2024-09-05 10:38 UTC, closed without merging