Coco rep
uyuni-project/uyuni-tools pull request #445
Opened 2024-09-04 12:06 UTC by mbussolotto

## What does this PR change?

**add description**

## Test coverage
- No tests

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/25193

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-09-04 13:51 UTC, cbosdo requested changes

2024-09-04 13:51 UTC, cbosdo commented on mgradm/cmd/install/podman/utils.go
> +	if flags.Coco.Replicas > 0 {
The setup should always be done so that it's easy to turn it on later. However in that case indeed the setup should not pull the image it the replica count is 0

2024-09-04 13:51 UTC, cbosdo commented on mgradm/cmd/install/podman/utils.go
> -	if err := hub.SetupHubXmlrpc(
Same for Hub

2024-09-10 13:15 UTC, cbosdo commented on mgradm/shared/hub/xmlrpcapi.go
>  	preparedImage, err := podman.PrepareImage(authFile, hubXmlrpcImage, pullPolicy)
and I thought you wanted to only execute the image preparation if there was a replica...

2024-09-23 14:56 UTC, mbussolotto commented on mgradm/shared/hub/xmlrpcapi.go
>  	preparedImage, err := podman.PrepareImage(authFile, hubXmlrpcImage, pullPolicy)
this was the idea...but it's quite complicated by now since the compute image name is too bound with the pull. I prefereed to handle the error. In this way we would have the systemd file with the correct image name but no failure if the image is not pulled

2024-09-23 14:58 UTC, mbussolotto commented on mgradm/shared/hub/xmlrpcapi.go
>  	preparedImage, err := podman.PrepareImage(authFile, hubXmlrpcImage, pullPolicy)
mmm actually you're right, I'll add this logic in `PrepareImage`

2024-09-23 15:13 UTC, mbussolotto commented on mgradm/shared/hub/xmlrpcapi.go
> +	}
Improve it checking if flag is changed (viper library)

2024-09-23 15:54 UTC, cbosdo approved these changes

2024-09-24 07:32 UTC, merged