uyuniadm subcommands
uyuni-project/uyuni-tools pull request #53
Opened 2023-09-25 16:37 UTC by cbosdo

Split `uyuniadm install` command into `uyuniadm install podman` and `uyuniadm install kubernetes` commands. This will make them clearly separated for conditional build in the future.

2023-09-25 16:37 UTC, cbosdo commented
Note: the function adding missing parameters seems to be broken

2023-09-25 17:15 UTC, rjmateus requested changes

2023-09-25 17:15 UTC, rjmateus commented on README.md
> +### Building in Open Build Service
this doesn't look to belong here

2023-09-25 17:15 UTC, rjmateus commented on uyuni-tools.spec
> +tag=%{!?_default_tag:latest}
this is also part of other PR

2023-09-25 17:15 UTC, rjmateus commented on uyuniadm/cmd/install/shared/flags.go
> +	Podman     cmd_utils.PodmanFlags
These podman and helm flags should be specific to the in use and not the share install flags

2023-09-25 17:15 UTC, rjmateus commented on uyuniadm/cmd/install/shared/flags.go
> +	cmd.Flags().Bool("debug", false, "Enable debugging features")
Sorry to get back to this, but we need to remove this flag or hide it with `cmd.Flags().MarkHidden("debug")`.
No customer or uyuni user will ever debug the code, and this will bring by providing a flag that a sub-set of people sometimes uses for development.

2023-09-26 03:57 UTC, cbosdo commented on uyuniadm/cmd/install/shared/flags.go
> +	cmd.Flags().Bool("debug", false, "Enable debugging features")
I have already told you that I don't agree with your approach and this is not a reason to remove such a useful flag!

2023-09-26 03:58 UTC, cbosdo commented on uyuni-tools.spec
> +tag=%{!?_default_tag:latest}
I simply forgot to fetch `main`

2023-09-26 03:59 UTC, cbosdo commented
> Note: the function adding missing parameters seems to be broken

Fixed: just had to squash the mapstructure for the anonymous type.

2023-09-26 09:28 UTC, rjmateus approved these changes

2023-09-26 09:36 UTC, merged