Shell auto completion
uyuni-project/uyuni-tools pull request #94
Opened 2023-11-06 21:28 UTC by NamelessOne91

2023-11-06 21:44 UTC, NamelessOne91 commented
Working on issue  #74: Shell auto-completion

I've added a shared cobra command  - completion -  to be used as sub-command both for uyuniadm and uyunictl root commands.
It leverages cobra's built in generation of shell completion scripts.

I had to do a minor refactor of the Logger's init method in order to avoid redirecting also the info welcome messages to the generated shell completion scripts.

2023-11-08 09:10 UTC, mbussolotto requested changes

2023-11-08 09:10 UTC, mbussolotto commented on build.sh
> +./bin/uyunictl completion bash >> "${COMPLETION_FILE}"
The two command should be run inside the spec file, in this way the completion would work out of the box installing uyuni-tools from RPM

2023-11-08 09:58 UTC, cbosdo commented on build.sh
> +./bin/uyunictl completion bash >> "${COMPLETION_FILE}"
Note that the completion files should be shipped in separate packages as done in this package for example: https://build.opensuse.org/package/view_file/devel:tools:scm/tig/tig.spec?expand=1

2023-11-08 10:05 UTC, cbosdo requested changes
May be you should squash all the commits into one: those are not huge changes and are all related.

2023-11-08 10:05 UTC, cbosdo commented on shared/completion/completion.go
> +			}
Do we need powershell completion since we are not building for windows? I would remove it.

2023-11-08 10:05 UTC, cbosdo commented on uyuniadm/cmd/cmd.go
> +		// do not log if running the completion cmd as the output is redirect
```suggestion
		// do not log if running the completion cmd as the output is redirected
```

2023-11-08 10:05 UTC, cbosdo commented on uyuniadm/cmd/cmd.go
> +		// to create a file to source
Can't this line fit with the previous one? We cut at 120 characters, may be that fits

2023-11-08 10:05 UTC, cbosdo commented on uyunictl/cmd/cmd.go
> +			log.Info().Msg("Welcome to uyuniadm")
Copy-paste issue:

```suggestion
			log.Info().Msg("Welcome to uyunictl")
```

2023-11-08 10:05 UTC, cbosdo commented on build.sh
> +COMPLETION_FILE="/tmp/completion"
Why this path in the `build.sh` script? Can't those be in `bin` folder too?

2023-11-08 10:05 UTC, cbosdo commented on README.md
> +The supported shells are: bash, zsh, fish and powershell.
I would remove `powershell` from the list. See the other comment on that.

2023-11-16 16:50 UTC, rjmateus commented
Thank you for your contribution, this is really cool stuff.
However, I'm not sure if the completion subcommand should be part of the existing commands. What do you guys think?
We could have a module that could be called to generate the completion for all flavors and it could be called at build time. to provide the data for the completion package.
@cbosdo @mbussolotto what do you think?

2023-11-16 16:59 UTC, mbussolotto commented
@rjmateus yes, I think we summarized everything here https://github.com/uyuni-project/uyuni-tools/pull/94#discussion_r1386313269 (not really readable since it was a comment on the code)

2023-11-16 19:13 UTC, cbosdo commented
> Thank you for your contribution, this is really cool stuff. However, I'm not sure if the completion subcommand should be part of the existing commands. What do you guys think? We could have a module that could be called to generate the completion for all flavors and it could be called at build time. to provide the data for the completion package. @cbosdo @mbussolotto what do you think?

If that is possible, then yes. Otherwise we could just hide those subcommands.

2023-12-04 16:34 UTC, cbosdo approved these changes
LGTM now

2023-12-04 17:17 UTC, cbosdo commented on uyunictl/cmd/cmd.go
> +			log.Info().Msg("Welcome to uyuniadm")
> is this supposed to really be uyuniadm? can we use a variable here or it doesn't work?

Right! we should probably use `os.Args[0]` to make it future-proof

2023-12-05 08:23 UTC, cbosdo commented on build.sh
> +    ./bin/uyunictl completion ${shell} >> "${COMPLETION_FILE}"
This is only for dev's use, but yes that's what it does.

2023-12-05 08:23 UTC, cbosdo commented on uyuni-tools.spec
> +Supplements:    (%{name_adm} and bash-completion)
The build failed with it for SLE 12, Debian and Ubuntu: this is why I added the condition on SUSE versions above and including 15

2023-12-05 08:24 UTC, cbosdo commented
Note that this PR is built successfully for all distros but AlmaLinux8 in https://build.opensuse.org/package/show/home:cbosdonnat:branches:systemsmanagement:Uyuni:Master:ContainerUtils/uyuni-tools

2023-12-05 08:42 UTC, mbussolotto approved these changes
LGTM!

2023-12-05 08:50 UTC, deneb-alpha approved these changes
LGTM, thanks!

2023-12-05 10:34 UTC, merged