Uninstall fix
uyuni-project/uyuni-tools pull request #95
Opened 2023-11-07 17:04 UTC by NamelessOne91

Issue #89

2023-11-08 09:48 UTC, cbosdo requested changes
Please drop the changes in the connection code as those would be leading to a lot of other issues. I am curious to know the reasons for those changes.

2023-11-08 09:48 UTC, cbosdo commented on shared/utils/connection.go
> +			c.command = c.backend
We want these two cases to check for the command to be in the `PATH`, so this change doesn't look OK

2023-11-08 09:48 UTC, cbosdo commented on shared/utils/connection.go
> +				err = fmt.Errorf("backend command not found in PATH: %s", c.backend)
Here `c.backend` is usually not set: this code ensures we have the `podman` , `podman-remote` or `kubectl` command in the `PATH` before using it. So better remove this change

2023-11-08 09:48 UTC, cbosdo commented on uyuniadm/cmd/uninstall/podman.go
> +			log.Debug().Msgf("Would remove %s", podman.ServicePath)
Thanks for spotting those typos!

2023-11-08 09:48 UTC, cbosdo commented on uyuniadm/cmd/uninstall/podman.go
> +			}
Thanks for adding that missing error check: this may help understanding the issue, but surely doesn't fix it.

2023-11-09 17:20 UTC, NamelessOne91 commented
Hi Cedric, thanks for the review.

I've dropped the changes to the connection-related code and kept only the additional error logs ATM.

As you stated in the issue's comments, the problem Michele had is likely due to not having a container named _uyuni-server_ running. This causes no backend to be picked up even if podman is present .
Is that working as intended ?

The lack of the `Msg` method call on line 28 of  [uninstall.go](https://github.com/uyuni-project/uyuni-tools/blob/main/uyuniadm/cmd/uninstall/uninstall.go)  may contribute to make this harder to spot.

Possible changes to the connection code are probably out of scope and may involve some refactoring, it might be better to discuss them as a separate topic.

2023-11-09 17:28 UTC, cbosdo commented
> As you stated in the issue's comments, the problem Michele had is likely due to not having a container named _uyuni-server_ running. This causes no backend to be picked up even if podman is present . Is that working as intended ?

No, this is not intended, but I haven't though very deeply how we should be handling that case. We probably need to try looking for other specific files and resources deployed early, like the systemd service file, the traefik config or similar.

> The lack of the `Msg` method call on line 28 of [uninstall.go](https://github.com/uyuni-project/uyuni-tools/blob/main/uyuniadm/cmd/uninstall/uninstall.go) may contribute to make this harder to spot.
> 
> Possible changes to the connection code are probably out of scope and may involve some refactoring, it might be better to discuss them as a separate topic.

Changing those is not easy and we should probably have a smarter detection only for uninstall in case nothing worked

2023-11-09 17:28 UTC, cbosdo approved these changes

2023-11-09 17:29 UTC, cbosdo commented
Could you please squash the two commits into one before I merge?

2023-11-09 17:44 UTC, NamelessOne91 commented
Done, thanks.

2023-11-10 07:31 UTC, cbosdo commented
I'll postpone the merge until Uyuni 2023.10 is out

2023-11-14 17:11 UTC, merged